### ISSUE TITLE
报错不知道作者还更吗 

### ISSUE THREAD

**Issue by zxczaq001** [Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server#1]
![image](https://user-images.githubusercontent.com/104310573/219876656-926aa1d1-cb0e-4c1f-8134-362e389a0c71.png)
私聊发送地图 QQ反馈：请选择上传位置（输入阿拉伯数字)
之后就报错了

**Comment by Umamusume-Agnes-Digital** [comment]
这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。

**Comment by zxczaq001** [comment]
> 这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。

不能远程换图吗 我用指令就报错的样子

**Comment by Umamusume-Agnes-Digital** [comment]
上传完地图服务器要重启加载地图，没加载怎么换?

**Comment by Umamusume-Agnes-Digital** [comment]
> > 这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。
> 
> 不能远程换图吗 我用指令就报错的样子

如果你设置了崩溃自动重启的话，rcon重启指令是“_restart”

**Comment by zxczaq001** [comment]
> > > 这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。
> > 
> > 
> > 不能远程换图吗 我用指令就报错的样子
> 
> 如果你设置了崩溃自动重启的话，rcon重启指令是“_restart”

rcon的换图也是“map xxxxx”吗

**Comment by Umamusume-Agnes-Digital** [comment]
> > > > 这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。
> > > 
> > > 
> > > 不能远程换图吗 我用指令就报错的样子
> > 
> > 
> > 如果你设置了崩溃自动重启的话，rcon重启指令是“_restart”
> 
> rcon的换图也是“map xxxxx”吗

是的，确保你上传地图后至少一次重启服务器，然后用map加建图指令，而且换图也相当于重启服务器，因此返回消息应该是“服务器无响应或者在换图”

**Comment by zxczaq001** [comment]
> > > 这样是我从私聊转群聊后遇到的一个bug，暂时办法修，建议先拉小号弄群上传吧，以后想通了再修。
> > 
> > 
> > 不能远程换图吗 我用指令就报错的样子
> 
> 如果你设置了崩溃自动重启的话，rcon重启指令是“_restart”

请问这个如何设置 我用的systemctl关了不会重启

**Comment by zxczaq001** [comment]
换了Supervisor可以自动重启了

**Comment by zxczaq001** [comment]
群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时

**Comment by Umamusume-Agnes-Digital** [comment]
> 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
群文件上传，首先需要env设置上传的用户的qq，看readme，
其次，地图群里需要选择路径确认，不存在则取消。

**Comment by zxczaq001** [comment]
> > 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
> > 群文件上传，首先需要env设置上传的用户的qq，看readme，
> > 其次，地图群里需要选择路径确认，不存在则取消。

嗯 我之前试的时候不设置上传用户QQ私聊发送也不会触发上传 设置了之后群里分享给群友又每次都会触发

**Comment by Umamusume-Agnes-Digital** [comment]
> > > 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
> > > 群文件上传，首先需要env设置上传的用户的qq，看readme，
> > > 其次，地图群里需要选择路径确认，不存在则取消。
> 
> 嗯 我之前试的时候不设置上传用户QQ私聊发送也不会触发上传 设置了之后群里分享给群友又每次都会触发

私聊显示什么报错吗

**Comment by zxczaq001** [comment]
> > > > 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
> > > > 群文件上传，首先需要env设置上传的用户的qq，看readme，
> > > > 其次，地图群里需要选择路径确认，不存在则取消。
> > 
> > 
> > 嗯 我之前试的时候不设置上传用户QQ私聊发送也不会触发上传 设置了之后群里分享给群友又每次都会触发
> 
> 私聊显示什么报错吗

![image](https://user-images.githubusercontent.com/104310573/224608003-e1d9ae12-626b-4531-89df-241a08bb8e23.png)
不加QQ私聊上传没报错 就是没反应

**Comment by Umamusume-Agnes-Digital** [comment]
> > > > > 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
> > > > > 群文件上传，首先需要env设置上传的用户的qq，看readme，
> > > > > 其次，地图群里需要选择路径确认，不存在则取消。
> > > 
> > > 
> > > 嗯 我之前试的时候不设置上传用户QQ私聊发送也不会触发上传 设置了之后群里分享给群友又每次都会触发
> > 
> > 私聊显示什么报错吗
> 
> ![image](https://user-images.githubusercontent.com/104310573/224608003-e1d9ae12-626b-4531-89df-241a08bb8e23.png)
> 不加QQ私聊上传没报错 就是没反应

这不是我的问题，是gocq设置里默认禁止了临时对话，因为这种方式更容易被检测封号。

给你几个方法
1，gocq的config中打开临时对话(不推荐)
2，给bot的qq设置允许任何人添加，这样就是单向好友，也是可以正常回复。

～还有一个疑问，以前我设置所有好友私聊能上传就感觉已经很过分了，你这居然还临时对话上传，真哈人～

**Comment by zxczaq001** [comment]
> > > > > > 群上传能不能整个开关 在群上传下载太慢了 私聊上传只要一分钟 群可能就要半小时
> > > > > > 群文件上传，首先需要env设置上传的用户的qq，看readme，
> > > > > > 其次，地图群里需要选择路径确认，不存在则取消。
> > > > 
> > > > 
> > > > 嗯 我之前试的时候不设置上传用户QQ私聊发送也不会触发上传 设置了之后群里分享给群友又每次都会触发
> > > 
> > > 
> > > 私聊显示什么报错吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/104310573/224608003-e1d9ae12-626b-4531-89df-241a08bb8e23.png)
> > 不加QQ私聊上传没报错 就是没反应
> 
> 这不是我的问题，是gocq设置里默认禁止了临时对话，因为这种方式更容易被检测封号。
> 
> 给你几个方法 1，gocq的config中打开临时对话(不推荐) 2，给bot的qq设置允许任何人添加，这样就是单向好友，也是可以正常回复。
> 
> ～还有一个疑问，以前我设置所有好友私聊能上传就感觉已经很过分了，你这居然还临时对话上传，真哈人～

草 这是我的机器人肯定有加好友啊
