### ISSUE TITLE
py3.8无法启动报错

### ISSUE THREAD

**Issue by mas-alone** [Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server#2]
环境是win11，py3.8
![QQ图片20230306115610](https://user-images.githubusercontent.com/52590027/223016324-d627853c-5c0e-4e51-9f3c-28a77fddb790.png)

启动的时候直接报错的。

**Comment by Umamusume-Agnes-Digital** [comment]
这是我没考虑3.8之前版本的写法，已经在预发布版本兼容，使用指令更新pip install  nonebot-plugin-l4d2-server==0.3.5b2

**Comment by mas-alone** [comment]
> 这是我没考虑3.8之前版本的写法，已经在预发布版本兼容，使用指令更新pip install nonebot-plugin-l4d2-server==0.3.5b2

感谢回复！目前报错这个
`ERROR: Ignored the following versions that require a different python version: 0.2.2 Requires-Python >=3.9,<4.0; 0.3.0 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement nonebot_plugin_txt2img>=0.3.0 (from nonebot-plugin-l4d2-server) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.2.0, 0.2.1)
ERROR: No matching distribution found for nonebot_plugin_txt2img>=0.3.0`

**Comment by Umamusume-Agnes-Digital** [comment]
更新你的软件源，我这边测试python3.8版本是没有问题，nonebot_plugin_txt2img==0.3.0版本是三周前就发过pypi的。如果有问题请到[点击这里](https://github.com/mobyw/nonebot-plugin-txt2img)提问，这不是我插件的问题

**Comment by mas-alone** [comment]
Special thanks
