### ISSUE TITLE
求生服务器指令无法连接

### ISSUE THREAD

**Issue by zxczaq001** [Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server#3]
![image](https://user-images.githubusercontent.com/104310573/223142670-326e5dd3-b88c-41e5-b116-200afa131b5d.png)
在服务器上使用127.0.0.1不行 但是用网卡上的IP就行  
我现在在家虚拟机上127.0.0.1不行 网卡上的IP也不行 公网IP也不行
端口和密码都对

**Comment by Umamusume-Agnes-Digital** [comment]
如果使用127.0.0.1地址
- 1，求生服务器和机器人nb端处于同一个服务器上。
如果不是不能使用。

- 2，如果是云服务器。
求生服务器启动地址是127.0.0.1而不是0.0.0.0，如果你使用过第三方软件使用rcon指令，那大概率是0.0.0.0，那么就是公网ip。如果是云服务器没有修改过参数，默认地址就是127.0.0.1(docket部署自行询问作者，这里说明的是steamcmd下载的情况)

- 3，如果是个人服务器。
请确保向运营商申请的公网ip是可用的。rcon方法适用于专用服务器，不一定适用于本地服务器(没试过)。主要看你求生服务器启动的时候显示的地址，是内网地址就填内网地址，是0.0.0.0就是公网。

- 4，作者没考虑过win服务器都情况。
你所说网卡地址应该是类似10.4.x.x的这种地址，是我描述有误，应该是linux系统下，按照readme部署求生服务器方法，默认是127.0.0.1地址。无论如何，这个地址都属于内网而不是公网，因此机器人和服务器处于同一个服务器上使用内网地址是没有问题的。

- 5，检查一些其他的事项。
例如防火墙开放端口。检查服务器的拉黑ip。

顺便一提，rcon只有这一个报错，无论是地址错误还是密码错误还是端口未开放，都是这个报错。

**Comment by zxczaq001** [comment]
![image](https://user-images.githubusercontent.com/104310573/223312281-407a9a9c-d6ad-45e5-be62-2c6209710b93.png)
搞定了 原来我bot使用poetry run python bot.py启动无法连接 使用nb run启动之后可以连了

**Comment by zxczaq001** [comment]
![image](https://user-images.githubusercontent.com/104310573/223313578-c58a25ee-8d63-485f-8e21-581e0fa62104.png)

还有个问题群里上传地图 反馈这个请选择上传位置就没有其它显示了 正常吗

**Comment by Umamusume-Agnes-Digital** [comment]
![image](https://user-images.githubusercontent.com/70925546/223314118-69f93e17-d9a1-4715-991d-8aab305a853a.png)
按照env设置里的路径列表的数量，选第一个就回答1
